import Link from 'next/link';
import type { StorefrontContext } from '@/lib/storefront/storefront-types';
import { CartCountBadge } from '@/components/cart-count';

function img(value?: string | null) { return value || '/artisan-hero.png'; }
function ProductCard({ product, storeSlug }: { product: any; storeSlug: string }) { return <Link href={`/artisan/${storeSlug}/product/${product.slug}`} className="group block overflow-hidden rounded-lg border border-line bg-white"><img src={img(product.product_images?.[0]?.image_url)} alt={product.name} className="aspect-square w-full object-cover transition group-hover:scale-105"/><div className="p-4"><p className="text-xs font-bold uppercase text-rust">{product.categories?.name}</p><h3 className="mt-1 font-black">{product.name}</h3><p className="mt-2 text-sm text-muted">{product.base_price == null ? 'Quote required' : `Rs. ${Number(product.base_price).toLocaleString('en-IN')}`}</p></div></Link>; }
function StorefrontNav({ context }: { context: StorefrontContext }) { return <header className="border-b border-line bg-white/90 px-4 py-3 backdrop-blur sm:px-6 lg:px-8"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4"><Link href={`/artisan/${context.seller.store_slug}`} className="font-serif text-2xl">{context.settings.logo_url ? <img src={context.settings.logo_url} alt={context.seller.store_name} className="h-10 max-w-40 object-contain"/> : context.seller.store_name}</Link><nav className="flex items-center gap-4 text-sm font-black"><Link href={`/artisan/${context.seller.store_slug}/products`}>Products</Link><Link href={`/artisan/${context.seller.store_slug}/collections`}>Collections</Link><Link href="/cart" className="relative rounded-lg border border-line px-3 py-2">Cart<CartCountBadge/></Link></nav></div></header>; }
function CollectionStrip({ context }: { context: StorefrontContext }) { return context.collections.length ? <section className="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8"><h2 className="font-serif text-3xl">Collections</h2><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{context.collections.map((collection) => <Link key={collection.id} href={`/artisan/${context.seller.store_slug}/collections/${collection.slug}`} className="rounded-lg border border-line bg-white p-5"><h3 className="font-black">{collection.name}</h3><p className="mt-2 text-sm text-muted">{collection.description || 'Explore this collection.'}</p></Link>)}</div></section> : null; }
function ProductsGrid({ context, large = false }: { context: StorefrontContext; large?: boolean }) { return <section className="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8"><h2 className="font-serif text-3xl">Featured Products</h2>{context.products.length ? <div className={`mt-5 grid gap-5 ${large ? 'sm:grid-cols-2 lg:grid-cols-3' : 'sm:grid-cols-2 lg:grid-cols-4'}`}>{context.products.map((product) => <ProductCard key={product.id} product={product} storeSlug={context.seller.store_slug}/>)}</div> : <div className="mt-5 rounded-lg border border-line bg-white p-8 text-muted">No live products yet.</div>}</section>; }
function Footer({ context }: { context: StorefrontContext }) { return <footer className="border-t border-line bg-white px-4 py-10 sm:px-6 lg:px-8"><div className="mx-auto flex max-w-7xl flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><h2 className="font-serif text-2xl">{context.seller.store_name}</h2><p className="text-sm text-muted">{context.settings.shipping_policy || 'Shipping and custom-order policies are shared by the artisan.'}</p></div><div className="flex flex-wrap gap-3 text-sm font-bold text-rust">{context.socialLinks.map((link) => <a key={link.id} href={link.url}>{link.platform}</a>)}</div></div></footer>; }

export function WarmEditorialTemplate({ context }: { context: StorefrontContext }) { return <main className="bg-paper"><StorefrontNav context={context}/><Hero context={context} align="story"/><CollectionStrip context={context}/><Story context={context}/><ProductsGrid context={context}/><Footer context={context}/></main>; }
export function CleanGridTemplate({ context }: { context: StorefrontContext }) { return <main className="bg-white"><StorefrontNav context={context}/><CompactHero context={context}/><ProductsGrid context={context}/><CollectionStrip context={context}/><Story context={context}/><Footer context={context}/></main>; }
export function PersonalizedGiftsTemplate({ context }: { context: StorefrontContext }) { return <main className="bg-sand/40"><StorefrontNav context={context}/><Hero context={context} align="gift"/><section className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8"><div className="rounded-xl bg-rust p-8 text-white"><h2 className="font-serif text-3xl">Made for names, dates, and moments.</h2><p className="mt-2 text-white/80">{context.settings.custom_order_cta_text || 'Request personalization from this artisan.'}</p></div></section><CollectionStrip context={context}/><ProductsGrid context={context}/><Footer context={context}/></main>; }
export function VisualPortfolioTemplate({ context }: { context: StorefrontContext }) { return <main className="bg-ink text-white"><StorefrontNav context={context}/><Hero context={context} dark/><ProductsGrid context={context} large/><Story context={context} dark/><Footer context={context}/></main>; }
export function BoutiqueBrandTemplate({ context }: { context: StorefrontContext }) { return <main className="bg-[#fbfaf7]"><StorefrontNav context={context}/><Hero context={context} align="boutique"/><CollectionStrip context={context}/><ProductsGrid context={context}/><section className="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8"><div className="rounded-xl border border-line bg-white p-8 text-center"><h2 className="font-serif text-3xl">Join the studio list</h2><p className="mt-2 text-muted">Newsletter placeholder for future storefront updates.</p></div></section><Footer context={context}/></main>; }

function Hero({ context, dark = false, align = 'story' }: { context: StorefrontContext; dark?: boolean; align?: string }) { return <section className={`px-4 py-12 sm:px-6 lg:px-8 ${dark ? 'bg-ink text-white' : ''}`}><div className="mx-auto grid max-w-7xl items-center gap-8 lg:grid-cols-[.9fr_1.1fr]"><div><p className="text-xs font-black uppercase tracking-[.12em] text-rust">{context.settings.announcement_text || context.seller.city || 'Artisan storefront'}</p><h1 className="mt-3 font-serif text-5xl leading-tight">{context.settings.hero_title || context.seller.store_name}</h1><p className={`mt-5 max-w-xl leading-8 ${dark ? 'text-white/70' : 'text-muted'}`}>{context.settings.hero_subtitle || context.seller.short_bio}</p>{context.settings.custom_orders_enabled ? <Link href={`/artisan/${context.seller.store_slug}/custom-order`} className="mt-7 inline-block rounded-lg bg-rust px-5 py-3 font-black text-white">{context.settings.custom_order_cta_text || 'Request custom order'}</Link> : null}</div><img src={img(context.settings.hero_image_url || context.seller.cover_image_url)} alt={context.seller.store_name} className="aspect-[4/3] w-full rounded-xl object-cover"/></div></section>; }
function CompactHero({ context }: { context: StorefrontContext }) { return <section className="border-b border-line bg-white px-4 py-10 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><h1 className="font-serif text-4xl">{context.seller.store_name}</h1><p className="mt-3 max-w-2xl text-muted">{context.settings.hero_subtitle || context.seller.short_bio}</p></div></section>; }
function Story({ context, dark = false }: { context: StorefrontContext; dark?: boolean }) { return <section className={`mx-auto max-w-5xl px-4 py-10 sm:px-6 lg:px-8 ${dark ? 'text-white' : ''}`}><h2 className="font-serif text-3xl">{context.settings.about_title || `About ${context.seller.store_name}`}</h2><p className={`mt-4 leading-8 ${dark ? 'text-white/70' : 'text-muted'}`}>{context.settings.about_content || context.settings.artisan_story || context.seller.full_story || context.seller.short_bio}</p><h3 className="mt-8 font-black">Craft process</h3><p className={`mt-2 leading-7 ${dark ? 'text-white/70' : 'text-muted'}`}>{context.settings.craft_process_content || 'Small-batch handmade work with careful finishing.'}</p></section>; }
