import type { Artisan, Category, ImageRef, Product } from "./types";

export const demoImage: ImageRef = { src: "/artisan-hero.png", alt: "Indian artisan studio with handmade pottery and warm natural light", position: "center" };

export const categories: Category[] = [
  { slug: "personalized-gifts", name: "Personalized Gifts", description: "Names, dates, messages, colors, and keepsakes made personal.", accent: "bg-rust", image: { ...demoImage, position: "42% 45%" } },
  { slug: "home-decor", name: "Home Decor", description: "Handmade planters, wall accents, tableware, and warm home details.", accent: "bg-sage", image: { ...demoImage, position: "58% 45%" } },
  { slug: "jewelry", name: "Jewellery", description: "Small-batch earrings, pendants, bangles, and gifting sets.", accent: "bg-marigold", image: { ...demoImage, position: "70% 50%" } },
  { slug: "scrapbooks", name: "Scrapbooks", description: "Memory books, printed frames, keepsake boxes, and custom albums.", accent: "bg-clay", image: { ...demoImage, position: "35% 52%" } },
  { slug: "candles", name: "Candles", description: "Hand-poured scents, festive sets, and gift-ready candles.", accent: "bg-sand", image: { ...demoImage, position: "62% 55%" } },
  { slug: "art-prints", name: "Art & Prints", description: "Illustrations, framed pieces, stationery, and studio prints.", accent: "bg-success", image: { ...demoImage, position: "48% 55%" } }
];

export const artisans: Artisan[] = [
  { storeSlug: "neha-crafts", storeName: "Neha Crafts", ownerName: "Neha Sharma", city: "Jaipur", state: "Rajasthan", category: "Terracotta", bio: "Hand-painted terracotta and festive decor made in small batches.", story: "Neha runs a home studio focused on painted clay pieces for festivals, weddings, and thoughtful everyday gifting. Every batch is planned around durable clay, hand-finished motifs, and careful packing for safe delivery.", quote: "I started with a simple love for clay. Today, it connects me with homes across the country.", process: "Hand-shaped, sun-dried, painted in small batches, sealed, and packed with recyclable cushioning.", materials: "Terracotta clay, mineral pigments, water-based sealants, cotton wrap, kraft packaging.", yearsExperience: 5, rating: 4.9, reviews: 218, followers: 1840, completedOrders: 345, status: "approved", avatar: { ...demoImage, position: "48% 42%", alt: "Portrait of Neha in her terracotta studio" }, cover: { ...demoImage, position: "center", alt: "Neha Crafts terracotta studio cover" } },
  { storeSlug: "anokhi-looms", storeName: "Anokhi Looms", ownerName: "Farah Khan", city: "Bagru", state: "Rajasthan", category: "Block Prints", bio: "Natural-dye table linen and textile gifts from a family print workshop.", story: "A small textile collective preserving block-print motifs while supporting modern home and gifting needs.", quote: "Every print carries a block, a hand, and a rhythm we learned from our families.", process: "Cotton is washed, printed with carved blocks, dried naturally, stitched, checked, and packed.", materials: "Cotton, natural dyes, carved wooden blocks, cotton thread, recycled paper tags.", yearsExperience: 8, rating: 4.8, reviews: 154, followers: 980, completedOrders: 224, status: "approved", avatar: { ...demoImage, position: "40% 44%", alt: "Farah at a block-printing worktable" }, cover: { ...demoImage, position: "35% 55%", alt: "Block printed textile studio cover" } },
  { storeSlug: "mira-resin-studio", storeName: "Mira Resin Studio", ownerName: "Mira Iyer", city: "Pune", state: "Maharashtra", category: "Resin Gifts", bio: "Personalized resin nameplates, trays, frames, and keepsake gifts.", story: "Mira turns names, dates, flowers, and small memories into polished custom pieces with clear approval steps.", quote: "The best gifts carry small details. I build each piece around that memory.", process: "Design mockup, buyer approval, resin pour, curing, polishing, quality check, and progress notes.", materials: "High-clarity resin, dried flowers, pigments, brass hooks, printed inserts, protective packaging.", yearsExperience: 4, rating: 4.7, reviews: 96, followers: 730, completedOrders: 176, status: "approved", avatar: { ...demoImage, position: "54% 44%", alt: "Mira preparing a custom resin gift" }, cover: { ...demoImage, position: "60% 48%", alt: "Mira Resin Studio custom gift workspace" } }
];

export const products: Product[] = [
  { slug: "hand-painted-diya-set", title: "Hand-painted diya set", artisanSlug: "neha-crafts", categorySlug: "home-decor", type: "ready", price: 899, priceLabel: "Rs. 899", description: "Ready-to-ship terracotta diya set with warm festive colorwork.", story: "Painted in a small Jaipur batch for festive tables, pooja corners, and thoughtful gifting.", materials: "Terracotta clay, mineral pigment, matte sealant.", care: "Wipe gently with a dry cloth. Keep away from prolonged moisture.", timeline: "Dispatches in 2 days", occasion: "Diwali gifting", customizable: false, stock: 34, colors: ["#B85C43", "#D8A55E"], features: ["SKU managed", "Gift packaging", "Verified artisan"], images: [{ ...demoImage, position: "58% 52%", alt: "Hand-painted terracotta diya set" }], rating: 4.8, reviewCount: 42 },
  { slug: "block-printed-table-runner", title: "Block-printed table runner", artisanSlug: "anokhi-looms", categorySlug: "home-decor", type: "ready", price: 1450, priceLabel: "Rs. 1,450", description: "Cotton runner printed with natural dyes and traditional Bagru motifs.", story: "A quiet table accent made with hand-carved blocks and soft natural colors.", materials: "Cotton, natural dye, cotton thread.", care: "Cold wash separately. Dry in shade.", timeline: "Dispatches in 3 days", occasion: "Housewarming", customizable: false, stock: 18, colors: ["#7E9478", "#EEE4D5"], features: ["Natural dyes", "Wash care included", "Limited batch"], images: [{ ...demoImage, position: "38% 52%", alt: "Block printed cotton table runner" }], rating: 4.9, reviewCount: 31 },
  { slug: "custom-resin-nameplate", title: "Personalized wooden name board", artisanSlug: "mira-resin-studio", categorySlug: "personalized-gifts", type: "customized", price: 2200, priceLabel: "From Rs. 2,200", description: "Choose names, colors, florals, and reference files before checkout.", story: "Designed for new homes and special rooms, with a proofing step before production begins.", materials: "Resin, pigment, dried florals, brass hardware.", care: "Clean with a soft cloth. Avoid direct afternoon sun.", timeline: "Production in 7-10 days", occasion: "New home", customizable: true, stock: null, colors: ["#B85C43", "#7E9478"], features: ["Dynamic customization fields", "Reference upload", "Progress notes"], images: [{ ...demoImage, position: "45% 48%", alt: "Personalized handmade name board" }], rating: 4.7, reviewCount: 25 },
  { slug: "brass-wedding-favors", title: "Brass wedding favors", artisanSlug: "neha-crafts", categorySlug: "personalized-gifts", type: "bespoke", price: null, priceLabel: "Quote required", description: "Consultation-based bulk gifting with quote, deposit, and milestones.", story: "For ceremonies, guest hampers, and family gifting that needs a thoughtful handmade touch.", materials: "Brass accents, terracotta inserts, cotton wrap, kraft boxes.", care: "Care instructions vary by selected gift set.", timeline: "Quote in 48 hours", occasion: "Wedding gifting", customizable: true, stock: null, colors: ["#B8955D", "#6D5F4F"], features: ["Budget range", "Milestone tracking", "Deposit workflow"], images: [{ ...demoImage, position: "64% 50%", alt: "Handmade brass wedding favor concept" }], rating: 4.9, reviewCount: 18 },
  { slug: "personalized-textile-pouch", title: "Personalized textile pouch", artisanSlug: "anokhi-looms", categorySlug: "scrapbooks", type: "customized", price: 680, priceLabel: "From Rs. 680", description: "Custom initials and motif options for small gifting runs.", story: "A useful keepsake for return gifts, team hampers, and travel sets.", materials: "Block-printed cotton, cotton lining, zipper, thread.", care: "Hand wash gently. Dry flat.", timeline: "Production in 5-7 days", occasion: "Return gifts", customizable: true, stock: null, colors: ["#B85C43", "#D8A55E"], features: ["Character limits", "Add-on pricing", "Bulk friendly"], images: [{ ...demoImage, position: "36% 52%", alt: "Personalized handmade textile pouch" }], rating: 4.6, reviewCount: 19 },
  { slug: "corporate-hamper-design", title: "Corporate hamper design", artisanSlug: "mira-resin-studio", categorySlug: "personalized-gifts", type: "bespoke", price: null, priceLabel: "From Rs. 8,000", description: "Bespoke enquiry for corporate gifting, quantity, delivery, and deadline.", story: "Curated handmade sets for teams, clients, festive gifting, and launch events.", materials: "Selected per quote: candles, printed goods, resin keepsakes, decor, packaging.", care: "Care notes included per selected items.", timeline: "Seller reviews in 24 hours", occasion: "Corporate gifting", customizable: true, stock: null, colors: ["#7E9478", "#B85C43"], features: ["Quote flow", "Deposit tracking", "Final payment status"], images: [{ ...demoImage, position: "70% 46%", alt: "Custom corporate handmade hamper concept" }], rating: 4.8, reviewCount: 12 }
];
export const occasions = ["Birthdays", "Weddings", "Anniversaries", "Housewarming", "Baby gifts", "Corporate gifting"];
export const getArtisan = (slug: string) => artisans.find((artisan) => artisan.storeSlug === slug);
export const getCategory = (slug: string) => categories.find((category) => category.slug === slug);
export const getProduct = (slug: string) => products.find((product) => product.slug === slug);
export const productsByArtisan = (storeSlug: string) => products.filter((product) => product.artisanSlug === storeSlug);
export const productsByCategory = (categorySlug: string) => products.filter((product) => product.categorySlug === categorySlug);
