import { redirect } from 'next/navigation';
import { AccountShell } from '@/components/account-shell';
import { requireAuth } from '@/lib/services/auth';
import { getBuyerAddresses } from '@/lib/services/account';
import { deleteAccountAddressAction, saveAccountAddressAction, setDefaultAccountAddressAction } from '../actions';

export const dynamic = 'force-dynamic';

export default async function AddressesPage({ searchParams }: { searchParams: Promise<Record<string,string|undefined>> }) {
  const user = await requireAuth();
  if (!user) redirect('/login?next=/account/addresses');
  const params = await searchParams;
  const addresses = await getBuyerAddresses(user.id);
  const editing = addresses.find((address: any) => address.id === params.edit);
  return <AccountShell title="Delivery addresses" copy="Manage saved addresses for checkout and order delivery.">{params.error ? <p className="mb-4 rounded-lg border border-rust/30 bg-rust/10 p-3 font-bold text-rust">{params.error}</p> : null}<div className="grid gap-5 lg:grid-cols-[1fr_360px]"><section className="grid gap-3">{addresses.map((address: any) => <article key={address.id} className="rounded-xl border border-line bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><h2 className="font-black">{address.label} {address.is_default ? <span className="rounded bg-sage/15 px-2 py-1 text-xs text-success">Default</span> : null}</h2><p className="mt-2 break-words text-sm leading-6 text-muted">{address.full_name}<br/>{address.phone}<br/>{address.address_line_1}{address.address_line_2 ? `, ${address.address_line_2}` : ''}<br/>{address.city}, {address.state} {address.postal_code}<br/>{address.country}</p></div><div className="flex flex-wrap gap-2"><a href={`/account/addresses?edit=${address.id}`} className="rounded-lg border border-line px-3 py-2 text-sm font-black">Edit</a>{!address.is_default ? <form action={setDefaultAccountAddressAction}><input type="hidden" name="id" value={address.id}/><button className="rounded-lg border border-line px-3 py-2 text-sm font-black">Make default</button></form> : null}<form action={deleteAccountAddressAction}><input type="hidden" name="id" value={address.id}/><button className="rounded-lg border border-rust/30 px-3 py-2 text-sm font-black text-rust">Delete</button></form></div></div></article>)}{!addresses.length ? <div className="rounded-xl border border-line bg-white p-8 text-muted">No saved addresses yet.</div> : null}</section><AddressForm address={editing} /></div></AccountShell>;
}

function AddressForm({ address }: { address?: any }) {
  return <form action={saveAccountAddressAction} className="grid h-fit gap-3 rounded-xl border border-line bg-white p-5"><h2 className="font-black">{address ? 'Edit address' : 'Add address'}</h2>{address ? <input type="hidden" name="id" value={address.id}/> : null}<Input name="label" label="Label" defaultValue={address?.label || 'Home'}/><Input name="full_name" label="Full name" defaultValue={address?.full_name || ''}/><Input name="phone" label="Phone" defaultValue={address?.phone || ''}/><Input name="address_line_1" label="Address line 1" defaultValue={address?.address_line_1 || ''}/><Input name="address_line_2" label="Address line 2" defaultValue={address?.address_line_2 || ''} required={false}/><Input name="city" label="City" defaultValue={address?.city || ''}/><Input name="state" label="State" defaultValue={address?.state || ''}/><Input name="postal_code" label="Postal code" defaultValue={address?.postal_code || ''}/><Input name="country" label="Country" defaultValue={address?.country || 'India'}/><label className="text-sm font-bold"><input name="is_default" type="checkbox" defaultChecked={address?.is_default}/> Make default</label><button className="rounded-lg bg-rust px-5 py-3 font-black text-white">Save address</button></form>;
}
function Input({ name, label, defaultValue = '', required = true }: { name: string; label: string; defaultValue?: string; required?: boolean }) { return <label className="grid gap-2 text-sm font-black"><span>{label}</span><input name={name} defaultValue={defaultValue} required={required} className="min-h-11 rounded-lg border border-line bg-paper px-4 outline-none"/></label>; }
