import { notFound } from 'next/navigation';
import { Badge, SectionHeading } from '@/components/ui';
import { getCustomOrderEntryContext } from '@/lib/services/custom-orders';
import { submitCustomOrderRequestAction } from '@/app/custom-orders/actions';

export const dynamic = 'force-dynamic';

export default async function ArtisanCustomOrderPage({ params, searchParams }: { params: Promise<{ storeSlug: string }>; searchParams: Promise<Record<string,string|undefined>> }) {
  const { storeSlug } = await params;
  const query = await searchParams;
  const context = await getCustomOrderEntryContext(storeSlug, query.product);
  if (!context) notFound();
  const next = `/artisan/${storeSlug}/custom-order${query.product ? `?product=${query.product}` : ''}`;
  return <main className="mx-auto max-w-5xl px-4 py-10 sm:px-6 lg:px-8"><SectionHeading eyebrow={context.seller.store_name} title="Discuss a custom order" copy="Share your requirement directly with the artisan. You will receive a quotation before any work begins." />{query.error ? <p className="mb-4 rounded-lg border border-rust/30 bg-rust/10 p-3 font-bold text-rust">{query.error}</p> : null}<div className="grid min-w-0 gap-5 lg:grid-cols-[.8fr_1.2fr]"><aside className="grid h-fit min-w-0 gap-4 rounded-xl border border-line bg-white p-4 sm:p-5"><img src={context.product?.product_images?.[0]?.image_url || context.seller.cover_image_url || '/artisan-hero.png'} alt="" className="aspect-[4/3] w-full rounded-lg object-cover"/><div className="min-w-0"><Badge tone="sage">Quotation first</Badge><h2 className="mt-3 break-words font-black">{context.product?.name || context.seller.store_name}</h2><p className="mt-2 break-words text-sm leading-6 text-muted">{context.product?.short_description || context.seller.short_bio}</p></div><div className="break-words rounded-lg bg-paper p-4 text-sm leading-6 text-muted">Best for wedding decor, corporate gifting, bulk handmade products, installations, custom hampers, and event-specific pieces.</div></aside><form action={submitCustomOrderRequestAction} className="grid min-w-0 gap-4 rounded-xl border border-line bg-white p-4 sm:p-5"><input type="hidden" name="seller_id" value={context.seller.id}/><input type="hidden" name="product_id" value={context.product?.id || ''}/><input type="hidden" name="next" value={next}/><Input name="title" label="Project title" placeholder="Wedding favour hampers for 120 guests"/><Textarea name="description" label="Requirement description" placeholder="Tell the artisan what you need, materials, size, theme, colours, and any event context."/><div className="grid min-w-0 gap-4 sm:grid-cols-2"><Input name="budget_min" label="Minimum budget" type="number" placeholder="5000"/><Input name="budget_max" label="Maximum budget" type="number" placeholder="15000"/></div><div className="grid min-w-0 gap-4 sm:grid-cols-2"><Input name="quantity" label="Quantity" type="number" placeholder="120"/><Input name="deadline" label="Preferred completion date" type="date"/></div><Input name="delivery_location" label="Delivery location" placeholder="Jaipur, Rajasthan"/><Textarea name="buyer_notes" label="Buyer notes" required={false} placeholder="Anything else the artisan should know?"/><label className="grid min-w-0 gap-2 text-sm font-black"><span>Reference images or PDF</span><input name="reference_files" type="file" multiple accept=".jpg,.jpeg,.png,.webp,.pdf" className="w-full min-w-0 rounded-lg border border-dashed border-line bg-paper px-4 py-3"/></label><button className="rounded-lg bg-rust px-5 py-3 font-black text-white">Submit Custom Request</button></form></div></main>;
}

function Input({ name, label, placeholder = '', type = 'text', required = true }: { name: string; label: string; placeholder?: string; type?: string; required?: boolean }) { return <label className="grid min-w-0 gap-2 text-sm font-black"><span>{label}</span><input name={name} type={type} required={required} placeholder={placeholder} className="min-h-11 w-full min-w-0 rounded-lg border border-line bg-paper px-4 outline-none"/></label>; }
function Textarea({ name, label, placeholder = '', required = true }: { name: string; label: string; placeholder?: string; required?: boolean }) { return <label className="grid min-w-0 gap-2 text-sm font-black"><span>{label}</span><textarea name={name} required={required} placeholder={placeholder} className="min-h-28 w-full min-w-0 rounded-lg border border-line bg-paper px-4 py-3 outline-none"/></label>; }
