import Link from 'next/link';
import { notFound, redirect } from 'next/navigation';
import { Badge, SectionHeading } from '@/components/ui';
import { getSellerOrder, requireBuyer } from '@/lib/services/checkout';
import { addProgressUpdateAction, confirmOrderAction, dispatchOrderAction, markReadyToShipAction, startProductionAction } from '../actions';

export const dynamic = 'force-dynamic';

function money(value: number) { return `Rs. ${Number(value || 0).toLocaleString('en-IN')}`; }
function hasCustomized(order: any) { return (order.order_items || []).some((item: any) => item.product_snapshot?.product_type === 'customized'); }

export default async function SellerOrderDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<Record<string,string|undefined>> }) {
  const user = await requireBuyer();
  if (!user) redirect('/login?next=/seller/orders');
  const { id } = await params;
  const query = await searchParams;
  const order = await getSellerOrder(id, user.id);
  if (!order) notFound();
  const address = order.shipping_address || {};
  return <main className="mx-auto max-w-6xl px-4 py-10 sm:px-6 lg:px-8"><SectionHeading eyebrow="Seller order" title={order.order_number} copy={`${order.status} · Buyer: ${order.profiles?.full_name || order.profiles?.email || 'Buyer'}`} action={<Link href="/seller/orders" className="rounded-lg border border-line px-4 py-3 font-black">All orders</Link>} />{query.error ? <p className="mb-4 rounded-lg border border-rust/30 bg-rust/10 p-3 font-bold text-rust">{query.error}</p> : null}<div className="grid gap-5 lg:grid-cols-[1fr_360px]"><section className="grid gap-4"><article className="rounded-xl border border-line bg-white p-5"><div className="flex flex-wrap items-center gap-2"><Badge>{order.status}</Badge>{hasCustomized(order) ? <Badge tone="sand">Customized workflow</Badge> : <Badge tone="sage">Ready-to-ship workflow</Badge>}</div><div className="mt-5 grid gap-4">{order.order_items?.map((item: any) => <div key={item.id} className="grid gap-3 rounded-lg bg-paper p-3 sm:grid-cols-[80px_1fr]"><img src={item.product_snapshot?.primary_image || '/artisan-hero.png'} alt="" className="h-20 w-20 rounded-lg object-cover"/><div><h2 className="font-black">{item.product_snapshot?.name || 'Product'}</h2><p className="text-sm text-muted">Qty {item.quantity} · {money(item.unit_price)}</p><Snapshot data={item.variant_data} title="Variant" /><Snapshot data={item.customization_data} title="Customization" /></div></div>)}</div></article><Timeline order={order} seller/><ProgressForm order={order}/></section><aside className="grid h-fit gap-4"><SellerActions order={order}/><article className="rounded-xl border border-line bg-white p-5"><h2 className="font-black">Ship to</h2><p className="mt-2 text-sm leading-6 text-muted">{address.full_name}<br/>{address.phone}<br/>{address.address_line_1}{address.address_line_2 ? `, ${address.address_line_2}` : ''}<br/>{address.city}, {address.state} {address.postal_code}</p></article><article className="rounded-xl border border-line bg-white p-5"><h2 className="font-black">Seller totals</h2><Line label="Subtotal" value={money(order.subtotal)} /><Line label="Commission" value={money(order.platform_commission)} /><Line label="Seller net" value={money(order.seller_net_amount)} strong /></article></aside></div></main>;
}

function SellerActions({ order }: { order: any }) {
  if (order.status === 'pending_payment') return <article className="rounded-xl border border-line bg-white p-5 text-sm font-bold text-muted">Fulfilment unlocks after payment is marked paid.</article>;
  if (order.status === 'paid') return <ActionForm action={confirmOrderAction} order={order} label="Confirm Order" />;
  if (order.status === 'seller_confirmed' && hasCustomized(order)) return <ActionForm action={startProductionAction} order={order} label="Start Production" />;
  if (order.status === 'seller_confirmed' || order.status === 'in_production') return <ActionForm action={markReadyToShipAction} order={order} label="Mark Ready to Ship" />;
  if (order.status === 'ready_to_ship') return <form action={dispatchOrderAction} className="grid gap-3 rounded-xl border border-line bg-white p-5"><h2 className="font-black">Dispatch order</h2><input type="hidden" name="order_id" value={order.id}/><input name="courier_name" required placeholder="Courier name" className="rounded-lg border border-line bg-paper px-4 py-3"/><input name="tracking_number" required placeholder="Tracking number" className="rounded-lg border border-line bg-paper px-4 py-3"/><input name="tracking_url" placeholder="Tracking URL optional" className="rounded-lg border border-line bg-paper px-4 py-3"/><button className="rounded-lg bg-rust px-5 py-3 font-black text-white">Mark Dispatched</button></form>;
  if (order.status === 'dispatched') return <article className="rounded-xl border border-line bg-white p-5 text-sm font-bold text-muted">Waiting for buyer delivery confirmation.</article>;
  return <article className="rounded-xl border border-line bg-white p-5 text-sm font-bold text-muted">No seller action required.</article>;
}
function ActionForm({ action, order, label }: { action: any; order: any; label: string }) { return <form action={action} className="rounded-xl border border-line bg-white p-5"><input type="hidden" name="order_id" value={order.id}/><button className="w-full rounded-lg bg-rust px-5 py-3 font-black text-white">{label}</button></form>; }
function ProgressForm({ order }: { order: any }) { return <form action={addProgressUpdateAction} encType="multipart/form-data" className="grid gap-3 rounded-xl border border-line bg-white p-5"><h2 className="font-black">Add Progress Update</h2><input type="hidden" name="order_id" value={order.id}/><input name="title" placeholder="Update title" className="rounded-lg border border-line bg-paper px-4 py-3"/><textarea name="message" placeholder="Message" className="min-h-24 rounded-lg border border-line bg-paper px-4 py-3"/><input name="files" type="file" multiple accept=".jpg,.jpeg,.png,.webp,.pdf" className="rounded-lg border border-line bg-paper px-4 py-3"/><label className="text-sm font-bold"><input name="is_visible_to_buyer" type="checkbox" defaultChecked/> Visible to buyer</label><button className="rounded-lg border border-line bg-paper px-5 py-3 font-black">Save update</button></form>; }
function Timeline({ order }: { order: any; seller?: boolean }) { return <article className="rounded-xl border border-line bg-white p-5"><h2 className="font-black">Timeline</h2><div className="mt-3 grid gap-3 text-sm">{(order.order_status_history || []).map((entry: any) => <p key={entry.id} className="rounded bg-paper p-3"><strong>{entry.status}</strong><br/><span className="text-muted">{entry.note || new Date(entry.created_at).toLocaleString()}</span></p>)}{(order.order_progress_updates || []).map((entry: any) => <p key={entry.id} className="rounded bg-sand/40 p-3"><strong>{entry.title}</strong><br/><span className="text-muted">{entry.message || 'Progress update'} {entry.is_visible_to_buyer ? '' : '(internal)'}</span></p>)}</div></article>; }
function Line({ label, value, strong = false }: { label: string; value: string; strong?: boolean }) { return <p className={`mt-3 flex justify-between ${strong ? 'border-t border-line pt-3 font-black' : 'text-sm text-muted'}`}><span>{label}</span><span>{value}</span></p>; }
function Snapshot({ title, data }: { title: string; data: any }) { const entries = Object.values(data || {}); if (!entries.length) return null; return <div className="mt-2 text-xs text-muted"><p className="font-black text-ink">{title}</p>{entries.map((entry: any, index) => <p key={index}>{entry.label || entry.name || 'Field'}: {entry.value || entry.name || entry.path || 'Private file attached'}</p>)}</div>; }
