import Link from 'next/link';
import { saveProductAction } from './actions';

const productTypes = [
  ['ready_to_ship', 'Ready to ship', 'Stocked items with dispatch timeline.'],
  ['customized', 'Customized', 'Personalized products with production timeline.'],
  ['bespoke', 'Bespoke', 'Quote-led work where pricing can start from a base amount.']
];

export function ProductForm({ product, categories }: { product?: any; categories: any[] }) {
  const variantRows = (product?.product_variants || []).map((variant: any) => `${variant.name} | ${variant.value} | ${variant.price_adjustment || 0} | ${variant.stock_quantity ?? ''}`).join('\n');
  const fieldRows = (product?.product_customization_fields || []).map((field: any) => `${field.label} | ${field.field_type} | ${field.is_required ? 'required' : 'optional'} | ${(field.options || []).join(', ')} | ${field.placeholder || ''}`).join('\n');
  const locked = product && product.status === 'pending_review';
  return <form action={saveProductAction} className="grid gap-6 rounded-xl border border-line bg-white p-6">
    {product ? <input type="hidden" name="product_id" value={product.id}/> : null}
    {locked ? <div className="rounded-lg border border-gold/30 bg-gold/10 p-4 text-sm font-bold text-ink">This product is pending review and is read-only until admin review.</div> : null}
    <fieldset disabled={locked} className="grid gap-6 disabled:opacity-70">
      <Step title="1. Basic details"><div className="grid gap-4 md:grid-cols-2"><Input name="name" label="Product name" defaultValue={product?.name || ''} required/><Input name="slug" label="Product slug" defaultValue={product?.slug || ''} required/></div><label className="grid gap-2 text-sm font-black">Marketplace category<select name="category_id" defaultValue={product?.category_id || ''} className="rounded-lg border border-line px-4 py-3" required><option value="">Select category</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><div className="grid gap-3 md:grid-cols-3">{productTypes.map(([value, title, copy]) => <label key={value} className="rounded-lg border border-line bg-paper p-4"><input name="product_type" type="radio" value={value} defaultChecked={(product?.product_type || 'ready_to_ship') === value}/> <strong>{title}</strong><p className="mt-2 text-xs text-muted">{copy}</p></label>)}</div><Input name="short_description" label="Short description" defaultValue={product?.short_description || ''}/><Textarea name="description" label="Full description" defaultValue={product?.description || ''}/></Step>
      <Step title="2. Pricing and availability"><div className="grid gap-4 md:grid-cols-3"><Input name="base_price" label="Base price" type="number" step="0.01" defaultValue={product?.base_price ?? ''}/><Input name="compare_at_price" label="Compare-at price" type="number" step="0.01" defaultValue={product?.compare_at_price ?? ''}/><Input name="shipping_fee" label="Shipping fee" type="number" step="0.01" defaultValue={product?.shipping_fee ?? 0}/><Input name="sku" label="SKU" defaultValue={product?.sku || ''}/><Input name="stock_quantity" label="Stock quantity" type="number" defaultValue={product?.stock_quantity ?? ''}/><Input name="dispatch_days" label="Dispatch days" type="number" defaultValue={product?.dispatch_days ?? ''}/><Input name="production_days" label="Production days" type="number" defaultValue={product?.production_days ?? ''}/></div><label className="text-sm font-bold"><input name="is_customizable" type="checkbox" defaultChecked={Boolean(product?.is_customizable)}/> This product supports personalization</label></Step>
      <Step title="3. Product images"><input name="images" type="file" multiple accept="image/png,image/jpeg,image/webp" className="rounded-lg border border-line px-4 py-3"/><Input name="image_alt" label="Alt text for uploaded images" defaultValue=""/><div className="grid gap-3 sm:grid-cols-2 md:grid-cols-4">{(product?.product_images || []).map((image: any) => <figure key={image.id} className="rounded-lg border border-line bg-paper p-3"><img src={image.image_url} alt={image.alt_text || product.name} className="aspect-square w-full rounded-md object-cover"/><figcaption className="mt-2 text-xs text-muted">{image.is_primary ? 'Primary image' : 'Product image'}</figcaption></figure>)}</div></Step>
      <Step title="4. Variants"><Textarea name="variants" label="Variants" defaultValue={variantRows} placeholder="Size | Small | 0 | 10&#10;Packaging | Gift box | 150 |"/><p className="text-xs text-muted">One row per variant: Name | Value | Price adjustment | Stock.</p></Step>
      <Step title="5. Customization fields"><Textarea name="customization_fields" label="Customization fields" defaultValue={fieldRows} placeholder="Name to print | text | required | | Enter name&#10;Packaging style | select | optional | Standard, Gift box | Choose packaging"/><p className="text-xs text-muted">Types: text, textarea, select, color, date, file, number.</p></Step>
      <Step title="6. Product details"><Textarea name="materials" label="Materials" defaultValue={product?.materials || ''}/><Textarea name="care_instructions" label="Care instructions" defaultValue={product?.care_instructions || ''}/><Textarea name="shipping_information" label="Shipping information" defaultValue={product?.shipping_information || ''}/><Textarea name="return_policy_note" label="Return-policy note" defaultValue={product?.return_policy_note || ''}/></Step>
      <Step title="7. Storefront collections"><Input name="collections" label="Seller collections" placeholder="Featured, Wedding Gifts, New Arrivals" defaultValue=""/><p className="text-xs text-muted">Marketplace categories are admin-controlled. Seller collections organize products inside your own storefront.</p></Step>
      <Step title="8. Review and submit"><div className="rounded-lg border border-line bg-paper p-5"><h2 className="font-black">Preview summary</h2><p className="mt-2 text-muted">Save a draft, preview the listing, or submit it for admin review. Sellers cannot publish directly.</p></div></Step>
    </fieldset>
    <div className="flex flex-col gap-3 sm:flex-row"><button name="intent" value="draft" className="rounded-lg border border-line bg-paper px-5 py-3 font-black" disabled={locked}>Save as Draft</button><button name="intent" value="preview" className="rounded-lg border border-rust px-5 py-3 font-black text-rust" disabled={locked}>Preview</button><button name="intent" value="submit" className="rounded-lg bg-rust px-5 py-3 font-black text-white" disabled={locked}>Submit for Review</button>{product ? <Link href={`/seller/products/${product.id}/preview`} className="rounded-lg border border-line px-5 py-3 text-center font-black">Private preview</Link> : null}</div>
  </form>;
}

function Step({ title, children }: { title: string; children: React.ReactNode }) { return <section className="grid gap-4 border-b border-line pb-6 last:border-0"><h2 className="font-serif text-2xl">{title}</h2>{children}</section>; }
function Input({ label, ...props }: any) { return <label className="grid gap-2 text-sm font-black">{label}<input {...props} className="rounded-lg border border-line px-4 py-3" /></label>; }
function Textarea({ label, ...props }: any) { return <label className="grid gap-2 text-sm font-black">{label}<textarea {...props} className="min-h-28 rounded-lg border border-line px-4 py-3" /></label>; }
