import Link from 'next/link';
import { notFound, redirect } from 'next/navigation';
import { Badge } from '@/components/ui';
import { AccountShell } from '@/components/account-shell';
import { requireAuth } from '@/lib/services/auth';
import { bespokeStatusLabels, customOrderNextAction } from '@/lib/types/custom-orders';
import { getBuyerCustomOrderRequestById } from '@/lib/services/custom-orders';
import { acceptCustomQuoteAction, declineCustomQuoteAction, requestQuoteRevisionAction } from '../actions';

export const dynamic = 'force-dynamic';

function money(value: number | null | undefined) { return value == null ? 'Not set' : `Rs. ${Number(value).toLocaleString('en-IN')}`; }
function date(value: string | null | undefined) { return value ? new Date(value).toLocaleDateString() : 'Not set'; }

export default async function BuyerCustomOrderDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<Record<string,string|undefined>> }) {
  const user = await requireAuth();
  if (!user) redirect('/login?next=/account/custom-orders');
  const { id } = await params;
  const query = await searchParams;
  const request = await getBuyerCustomOrderRequestById(id, user.id);
  if (!request) notFound();
  const quotes = request.custom_order_quotes || [];
  const latest = quotes[0];
  const payments = request.custom_order_payment_records || [];
  return <AccountShell title={request.request_number} copy={`${request.title} / ${bespokeStatusLabels[request.status] || request.status}`}>{query.error ? <p className="mb-4 rounded-lg border border-rust/30 bg-rust/10 p-3 font-bold text-rust">{query.error}</p> : null}<div className="mb-4"><Link href="/account/custom-orders" className="inline-flex rounded-lg border border-line bg-white px-4 py-3 font-black">All custom orders</Link></div><div className="grid gap-5 xl:grid-cols-[1fr_340px]"><section className="grid gap-4"><article className="rounded-xl border border-line bg-white p-5"><div className="flex flex-wrap gap-2"><Badge>{request.status}</Badge><Badge tone="sage">{customOrderNextAction(request.status)}</Badge></div><p className="mt-4 leading-7 text-muted">{request.description}</p><div className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><Info label="Budget" value={`${money(request.budget_min)} - ${money(request.budget_max)}`}/><Info label="Quantity" value={String(request.quantity || 'Not set')}/><Info label="Deadline" value={date(request.deadline)}/><Info label="Delivery location" value={request.delivery_location || 'Not set'}/></div></article><QuotePanel request={request} quote={latest}/><Milestones milestones={request.custom_order_milestones || []}/><Timeline history={request.custom_order_status_history || []}/></section><aside className="grid h-fit gap-4"><article className="rounded-xl border border-line bg-white p-5"><h2 className="font-black">Artisan</h2><Link href={`/artisan/${request.seller_profiles?.store_slug}`} className="mt-2 block font-black text-rust">{request.seller_profiles?.store_name}</Link><p className="mt-2 text-sm text-muted">Product: {request.products?.name || 'General custom enquiry'}</p></article><article className="rounded-xl border border-line bg-white p-5"><h2 className="font-black">Payment status</h2>{payments.length ? payments.map((payment: any) => <p key={payment.id} className="mt-3 flex justify-between gap-3 text-sm"><span>{payment.payment_type}</span><strong>{money(payment.amount)} / {payment.status}</strong></p>) : <p className="mt-2 text-sm text-muted">Payment records appear after quote acceptance.</p>}</article><article className="rounded-xl border border-line bg-white p-5"><h2 className="font-black">References</h2>{(request.reference_files || []).length ? <div className="mt-3 grid gap-2 text-sm text-muted">{request.reference_files.map((file: any) => <p className="break-all" key={file.storagePath}>{file.name}</p>)}</div> : <p className="mt-2 text-sm text-muted">No reference files uploaded.</p>}<Link href="/account/support" className="mt-4 inline-flex rounded-lg border border-line px-4 py-3 text-sm font-black">Need support?</Link></article></aside></div></AccountShell>;
}

function QuotePanel({ request, quote }: { request: any; quote: any }) {
  if (!quote) return <article className="rounded-xl border border-line bg-white p-5"><h2 className="font-black">Latest quote</h2><p className="mt-2 text-sm text-muted">The artisan has not sent a quote yet.</p></article>;
  return <article className="rounded-xl border border-line bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-black">Latest quote v{quote.quote_version}</h2><Badge>{quote.status}</Badge></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><Info label="Quote total" value={money(quote.quote_amount)}/><Info label="Deposit" value={money(quote.deposit_amount)}/><Info label="Final amount" value={money(quote.final_amount)}/></div><p className="mt-3 text-sm leading-6 text-muted">{quote.quote_notes || 'No additional notes.'}</p>{request.status === 'quote_sent' ? <div className="mt-4 grid gap-3 sm:grid-cols-3"><form action={acceptCustomQuoteAction}><input type="hidden" name="request_id" value={request.id}/><button className="w-full rounded-lg bg-rust px-4 py-3 font-black text-white">Accept Quote</button></form><form action={requestQuoteRevisionAction} className="grid gap-2"><input type="hidden" name="request_id" value={request.id}/><input name="revision_note" placeholder="Revision note" className="rounded-lg border border-line bg-paper px-3 py-2 text-sm"/><button className="rounded-lg border border-line px-4 py-3 font-black">Request Revision</button></form><form action={declineCustomQuoteAction}><input type="hidden" name="request_id" value={request.id}/><button className="w-full rounded-lg border border-rust/30 px-4 py-3 font-black text-rust">Decline</button></form></div> : null}</article>;
}
function Milestones({ milestones }: { milestones: any[] }) { return <article className="rounded-xl border border-line bg-white p-5"><h2 className="font-black">Milestones</h2>{milestones.length ? <div className="mt-4 grid gap-3">{milestones.map((item) => <div key={item.id} className="rounded-lg bg-paper p-3"><div className="flex flex-wrap justify-between gap-2"><strong>{item.title}</strong><Badge>{item.status}</Badge></div><p className="mt-1 text-sm text-muted">{item.description}</p>{(item.image_paths || []).length ? <p className="mt-2 break-all text-xs text-muted">{item.image_paths.map((file: any) => file.name || file.storagePath).join(', ')}</p> : null}</div>)}</div> : <p className="mt-2 text-sm text-muted">Milestones appear after production starts.</p>}</article>; }
function Timeline({ history }: { history: any[] }) { return <article className="rounded-xl border border-line bg-white p-5"><h2 className="font-black">Timeline</h2><div className="mt-4 grid gap-3">{history.map((entry) => <div key={entry.id} className="rounded-lg bg-paper p-3 text-sm"><strong>{bespokeStatusLabels[entry.status] || entry.status}</strong><p className="text-muted">{entry.note || 'Status updated.'}</p></div>)}</div></article>; }
function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-lg bg-paper p-3"><p className="text-xs font-bold uppercase tracking-[.08em] text-muted">{label}</p><p className="mt-1 break-words font-black">{value}</p></div>; }
