import { notFound } from "next/navigation";
import { ArtisanCard, Badge, ProductGrid, SectionHeading } from "@/components/ui";
import { AddToCartForm } from "@/components/add-to-cart-form";
import { getArtisanStorefrontBySlug, getProductBySlug, getRelatedProducts } from "@/lib/services/public-marketplace";
import { getPublicProductBySlug } from "@/lib/services/products";

export default async function ProductPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const { data: rawProduct } = await getPublicProductBySlug(slug);
  if (!rawProduct) notFound();
  const mappedProduct = await getProductBySlug(slug);
  if (!mappedProduct) notFound();
  const [artisan, related] = await Promise.all([getArtisanStorefrontBySlug(mappedProduct.artisanSlug), getRelatedProducts(mappedProduct.slug, mappedProduct.categorySlug, 4)]);
  const images = rawProduct.product_images?.length ? rawProduct.product_images : [{ id: 'fallback', image_url: '/artisan-hero.png', alt_text: rawProduct.name }];
  return <main className="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8"><div className="grid gap-10 lg:grid-cols-[1.05fr_.95fr]"><div className="grid gap-3"><img src={images[0].image_url} alt={images[0].alt_text || rawProduct.name} className="aspect-square w-full rounded-xl border border-line object-cover"/><div className="grid grid-cols-4 gap-3">{images.slice(0,4).map((image: any) => <img key={image.id} src={image.image_url} alt={image.alt_text || rawProduct.name} className="aspect-square rounded-lg border border-line object-cover"/>)}</div></div><section><Badge>{rawProduct.product_type === 'ready_to_ship' ? 'Ready to Ship' : rawProduct.product_type === 'customized' ? 'Customizable' : 'Made to Order'}</Badge><h1 className="mt-4 font-serif text-4xl leading-tight sm:text-5xl">{rawProduct.name}</h1><p className="mt-3 text-sm font-black text-sage">{rawProduct.seller_profiles?.store_name}</p><p className="mt-5 leading-7 text-muted">{rawProduct.description || rawProduct.short_description}</p>{rawProduct.product_type === 'ready_to_ship' ? <p className="mt-3 text-sm font-bold text-muted">Stock: {rawProduct.stock_quantity ?? 0}</p> : null}<AddToCartForm product={rawProduct} next={`/product/${rawProduct.slug}`} /></section></div><section className="mt-14 grid gap-5 lg:grid-cols-3"><article className="rounded-xl border border-line bg-white p-6"><h2 className="font-black">Product story</h2><p className="mt-3 leading-7 text-muted">{rawProduct.description || rawProduct.short_description}</p></article><article className="rounded-xl border border-line bg-white p-6"><h2 className="font-black">Materials and care</h2><p className="mt-3 leading-7 text-muted">{rawProduct.materials || 'Handmade materials'}</p><p className="mt-3 leading-7 text-muted">{rawProduct.care_instructions || 'Care guide included with order.'}</p></article><article className="rounded-xl border border-line bg-white p-6"><h2 className="font-black">Customization details</h2><p className="mt-3 leading-7 text-muted">{rawProduct.product_type === 'customized' ? "Complete required personalization fields before adding this item to cart." : rawProduct.product_type === 'bespoke' ? "This product starts with a custom quote." : "This item is ready to ship."}</p></article></section>{artisan ? <section className="mt-14"><SectionHeading eyebrow="Artisan" title="Made by an approved storefront" /><ArtisanCard artisan={artisan}/></section> : null}<section className="mt-14"><SectionHeading eyebrow="More like this" title="Explore similar handmade pieces" /><ProductGrid items={related}/></section></main>;
}
