insert into auth.users (id, instance_id, aud, role, email, encrypted_password, email_confirmed_at, confirmation_token, recovery_token, email_change_token_new, raw_app_meta_data, raw_user_meta_data, created_at, updated_at)
values ('20000000-0000-0000-0000-000000000100','00000000-0000-0000-0000-000000000000','authenticated','authenticated','demo.neha@example.com','',now(),'','','','{"provider":"email","providers":["email"]}'::jsonb,'{"full_name":"Neha Sharma"}'::jsonb,now(),now())
on conflict (id) do nothing;

insert into public.profiles (id, email, full_name, role)
values ('20000000-0000-0000-0000-000000000100','demo.neha@example.com','Neha Sharma','seller')
on conflict (id) do update set full_name = excluded.full_name, role = excluded.role, updated_at = now();

insert into public.seller_profiles (id, user_id, store_name, store_slug, short_bio, full_story, profile_image_url, cover_image_url, primary_category_id, years_experience, city, state, average_production_days, shipping_regions, supports_ready_to_ship, supports_customized, supports_bespoke, status, reviewed_at)
values ('30000000-0000-0000-0000-000000000100','20000000-0000-0000-0000-000000000100','Neha Crafts','neha-crafts','Hand-painted terracotta, festive decor, and custom wedding favors made in small batches.','Neha Crafts is a Jaipur home studio creating terracotta decor, hand-painted festive pieces, and bespoke gifting sets for celebrations and small businesses.','/artisan-hero.png','/artisan-hero.png','10000000-0000-0000-0000-000000000002',8,'Jaipur','Rajasthan',8,'["India"]'::jsonb,true,true,true,'approved',now())
on conflict (store_slug) do update set store_name = excluded.store_name, short_bio = excluded.short_bio, full_story = excluded.full_story, status = excluded.status, reviewed_at = excluded.reviewed_at;

insert into public.storefront_settings (seller_id, template_key, custom_subdomain, hero_title, hero_subtitle, about_title, about_content, artisan_story, craft_process_content, custom_order_cta_text, is_published)
values ('30000000-0000-0000-0000-000000000100','warm-editorial','neha-crafts','Neha Crafts, Jaipur','Hand-painted terracotta, festive decor, and custom wedding favors made in small batches.','About Neha Crafts','Every piece starts with simple clay forms, hand-painted motifs, and careful finishing for homes, festivals, and gifting.','Neha works from a small Jaipur studio, balancing ready-to-ship festive collections with personal commissions for weddings and family celebrations.','Small batches are shaped, painted, sealed, packed, and dispatched with clear timelines for custom work.','Request a custom piece',true)
on conflict (seller_id) do update set template_key = excluded.template_key, custom_subdomain = excluded.custom_subdomain, hero_title = excluded.hero_title, hero_subtitle = excluded.hero_subtitle, about_title = excluded.about_title, about_content = excluded.about_content, artisan_story = excluded.artisan_story, craft_process_content = excluded.craft_process_content, custom_order_cta_text = excluded.custom_order_cta_text, is_published = excluded.is_published;

insert into public.products (seller_id, category_id, name, slug, short_description, description, product_type, status, base_price, stock_quantity, dispatch_days, production_days, shipping_fee, is_featured, is_customizable, materials, care_instructions)
values
  ('30000000-0000-0000-0000-000000000100','10000000-0000-0000-0000-000000000002','Painted Diya Set','neha-painted-diya-set','Ready-to-ship festive terracotta diya set.','A hand-painted terracotta diya set for festive decor and gifting.','ready_to_ship','active',899,18,3,null,80,true,false,'Terracotta, acrylic color, sealant','Wipe with a soft dry cloth.'),
  ('30000000-0000-0000-0000-000000000100','10000000-0000-0000-0000-000000000002','Custom Nameplate Commission','neha-custom-nameplate','Personalized terracotta nameplate with colors and motif options.','A customized nameplate designed with buyer-selected names, palette, and motifs.','customized','active',2200,null,null,9,120,false,true,'Terracotta, paint, protective sealant','Keep away from direct heavy rain.'),
  ('30000000-0000-0000-0000-000000000100','10000000-0000-0000-0000-000000000001','Wedding Favor Hamper','neha-wedding-favor-hamper','Quote-based handmade favor sets for celebrations.','A bespoke gifting flow for bulk wedding favors, packaging, and personalization.','bespoke','active',null,null,null,21,0,false,true,'Terracotta, paper packaging, ribbon','Care instructions depend on selected pieces.')
on conflict (slug) do update set name = excluded.name, short_description = excluded.short_description, description = excluded.description, status = excluded.status;
