'use server';
import { revalidatePath } from 'next/cache';
import { redirect } from 'next/navigation';
import { requireAdmin } from '@/lib/services/auth';
import { createAdminClient } from '@/lib/supabase/admin';
export async function markSellerUnderReview(formData: FormData) { await requireAdmin(); const id = String(formData.get('sellerId')); const supabase = createAdminClient(); await supabase.from('seller_profiles').update({ status: 'under_review' }).eq('id', id); revalidatePath('/admin/sellers'); revalidatePath(`/admin/sellers/${id}`); }
export async function approveSellerAction(formData: FormData) { const admin = await requireAdmin(); const id = String(formData.get('sellerId')); const supabase = createAdminClient(); const { data: seller } = await supabase.from('seller_profiles').update({ status: 'approved', reviewed_by: admin.id, reviewed_at: new Date().toISOString(), rejection_reason: null }).eq('id', id).select('*').single(); if (seller) { await supabase.from('profiles').update({ role: 'seller' }).eq('id', seller.user_id); await supabase.from('notifications').insert({ user_id: seller.user_id, title: 'Seller application approved', message: 'Your artisan storefront has been approved.' }); } revalidatePath('/admin/sellers'); revalidatePath(`/admin/sellers/${id}`); }
export async function rejectSellerAction(formData: FormData) { const admin = await requireAdmin(); const id = String(formData.get('sellerId')); const reason = String(formData.get('reason') || '').trim(); if (!reason) redirect(`/admin/sellers/${id}?error=Rejection reason is required`); const supabase = createAdminClient(); const { data: seller } = await supabase.from('seller_profiles').update({ status: 'rejected', rejection_reason: reason, reviewed_by: admin.id, reviewed_at: new Date().toISOString() }).eq('id', id).select('*').single(); if (seller) await supabase.from('notifications').insert({ user_id: seller.user_id, title: 'Seller application needs updates', message: reason }); revalidatePath('/admin/sellers'); revalidatePath(`/admin/sellers/${id}`); }
export async function suspendSellerAction(formData: FormData) { const admin = await requireAdmin(); const id = String(formData.get('sellerId')); const reason = String(formData.get('reason') || 'Suspended by admin'); const supabase = createAdminClient(); await supabase.from('seller_profiles').update({ status: 'suspended', rejection_reason: reason, reviewed_by: admin.id, reviewed_at: new Date().toISOString() }).eq('id', id); revalidatePath('/admin/sellers'); revalidatePath(`/admin/sellers/${id}`); }
