import Link from 'next/link';
import { notFound, redirect } from 'next/navigation';
import { Badge } from '@/components/ui';
import { AccountShell } from '@/components/account-shell';
import { getBuyerOrder, requireBuyer } from '@/lib/services/checkout';
import { confirmDeliveryAction, reportOrderIssueAction } from '../actions';

export const dynamic = 'force-dynamic';

function money(value: number) { return `Rs. ${Number(value || 0).toLocaleString('en-IN')}`; }

export default async function BuyerOrderDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<Record<string,string|undefined>> }) {
  const user = await requireBuyer();
  if (!user) redirect('/login?next=/account/orders');
  const { id } = await params;
  const query = await searchParams;
  const order = await getBuyerOrder(id, user.id);
  if (!order) notFound();
  const address = order.shipping_address || {};
  const visibleUpdates = (order.order_progress_updates || []).filter((entry: any) => entry.is_visible_to_buyer);
  return <AccountShell title={order.order_number} copy={`From ${order.seller_profiles?.store_name || 'Artisan'} / ${order.status}`}>{query.error ? <p className="mb-4 rounded-lg border border-rust/30 bg-rust/10 p-3 font-bold text-rust">{query.error}</p> : null}<div className="mb-4"><Link href="/account/orders" className="inline-flex rounded-lg border border-line bg-white px-4 py-3 font-black">All orders</Link></div><div className="grid gap-5 xl:grid-cols-[1fr_340px]"><section className="grid gap-4"><article className="rounded-xl border border-line bg-white p-5"><div className="flex flex-wrap gap-2"><Badge>{order.status}</Badge>{order.tracking_number ? <Badge tone="sage">Tracking added</Badge> : null}</div><div className="mt-5 grid gap-4">{order.order_items?.map((item: any) => <div key={item.id} className="grid gap-3 rounded-lg bg-paper p-3 sm:grid-cols-[80px_1fr]"><img src={item.product_snapshot?.primary_image || '/artisan-hero.png'} alt="" className="h-20 w-20 rounded-lg object-cover"/><div className="min-w-0"><h2 className="break-words font-black">{item.product_snapshot?.name || 'Product'}</h2><p className="text-sm text-muted">Qty {item.quantity} / {money(item.unit_price)}</p><Snapshot data={item.variant_data} title="Variant" /><Snapshot data={item.customization_data} title="Personalization" /></div></div>)}</div></article><Timeline order={order} updates={visibleUpdates}/><IssueForm order={order}/></section><aside className="grid h-fit gap-4"><article className="rounded-xl border border-line bg-white p-5"><h2 className="font-black">Delivery address</h2><p className="mt-2 break-words text-sm leading-6 text-muted">{address.full_name}<br/>{address.address_line_1}{address.address_line_2 ? `, ${address.address_line_2}` : ''}<br/>{address.city}, {address.state} {address.postal_code}<br/>{address.phone}</p></article><article className="rounded-xl border border-line bg-white p-5"><h2 className="font-black">Tracking</h2>{order.tracking_number ? <p className="mt-2 break-words text-sm leading-6 text-muted">{order.courier_name}<br/>{order.tracking_number}<br/>{order.tracking_url ? <a className="font-bold text-rust" href={order.tracking_url}>Open tracking</a> : null}</p> : <p className="mt-2 text-sm text-muted">Tracking will appear after dispatch.</p>}{order.status === 'dispatched' ? <form action={confirmDeliveryAction} className="mt-4"><input type="hidden" name="order_id" value={order.id}/><button className="w-full rounded-lg bg-rust px-5 py-3 font-black text-white">Confirm Delivery Received</button></form> : null}</article><article className="rounded-xl border border-line bg-white p-5"><h2 className="font-black">Price summary</h2><Line label="Subtotal" value={money(order.subtotal)} /><Line label="Shipping" value={money(order.shipping_fee)} /><Line label="Total" value={money(order.total_amount)} strong /></article></aside></div></AccountShell>;
}

function Timeline({ order, updates }: { order: any; updates: any[] }) { const labels = ['pending_payment','paid','seller_confirmed','in_production','ready_to_ship','dispatched','delivered','completed']; return <article className="rounded-xl border border-line bg-white p-5"><h2 className="font-black">Timeline</h2><div className="mt-4 grid gap-3">{labels.map((status) => <div key={status} className={`rounded-lg border p-3 text-sm ${order.status === status ? 'border-rust bg-rust/10' : 'border-line bg-paper'}`}><strong>{status.replaceAll('_',' ')}</strong></div>)}{updates.map((entry) => <div key={entry.id} className="rounded-lg bg-sand/40 p-3 text-sm"><strong>{entry.title}</strong><p className="text-muted">{entry.message || 'Progress update'}</p></div>)}</div></article>; }
function IssueForm({ order }: { order: any }) { return <form action={reportOrderIssueAction} encType="multipart/form-data" className="grid gap-3 rounded-xl border border-line bg-white p-5"><h2 className="font-black">Report an Issue</h2><input type="hidden" name="order_id" value={order.id}/><select name="issue_type" className="rounded-lg border border-line bg-paper px-4 py-3"><option value="delivery_delay">Delivery delay</option><option value="damaged_item">Damaged item</option><option value="incorrect_item">Incorrect item</option><option value="customization_issue">Customization issue</option><option value="missing_item">Missing item</option><option value="other">Other</option></select><input name="subject" placeholder="Subject" className="rounded-lg border border-line bg-paper px-4 py-3"/><textarea name="description" placeholder="Describe the issue" className="min-h-24 rounded-lg border border-line bg-paper px-4 py-3"/><input name="files" type="file" multiple accept=".jpg,.jpeg,.png,.webp,.pdf" className="rounded-lg border border-line bg-paper px-4 py-3"/><button className="rounded-lg border border-line bg-paper px-5 py-3 font-black">Submit issue</button></form>; }
function Line({ label, value, strong = false }: { label: string; value: string; strong?: boolean }) { return <p className={`mt-3 flex justify-between gap-3 ${strong ? 'border-t border-line pt-3 font-black' : 'text-sm text-muted'}`}><span>{label}</span><span>{value}</span></p>; }
function Snapshot({ title, data }: { title: string; data: any }) { const entries = Object.values(data || {}); if (!entries.length) return null; return <div className="mt-2 text-xs text-muted"><p className="font-black text-ink">{title}</p>{entries.map((entry: any, index) => <p className="break-words" key={index}>{entry.label || entry.name || 'Field'}: {entry.value || entry.name || entry.path || 'Private file attached'}</p>)}</div>; }
